### ISSUE TITLE
Not able to convert norwegian characters

### ISSUE THREAD

**Issue by lroal** [mvz/msgconvert#4]
When converting an msg that was originally sent from an gmail account, it is not able to convert the norwegian characters. When converting an msg that is created in outlook, norwegian characters are correct. Could it be caused by gmail sending as unicode ? Is it possible to fix this ?

**Comment by mvz** [comment]
It's probably related to the character encoding indeed. Is the first email shown correctly in Outlook itself?

Msgconvert should output some warnings if it encounters an unknown encoding. Can you post its output please?

**Comment by lroal** [comment]
Yes, the first email is shown correctly in Outlook itself.
The .msg is here: https://drive.google.com/file/d/0B9QeKl4scmPSaFFja1E1WVF3dDg/view?usp=sharing

And here are the warnings:

Skipping DIR entry __nameid_version1 0 (Introductory stuff)
Skipping property 001F:5FE5 (UNKNOWN): sip:lars.roald@timpex.no
Using    property 001F:3002 (TYPE): EX
Skipping property 0102:0FF6 (Instance Key): 00 00 00 00 
Using    property 001F:3001 (NAME): Lars-Erik Roald
Skipping property 0003:3000 (Row Id): 0
Using    property 001F:3003 (ADDRESS): /O=NETSENTRAL/OU=First Administrative Gro ...
Skipping property 001F:3A20 (Transmittable Display Name): Lars-Erik Roald
Skipping property 0003:3900 (Address Book Display Type): 0
Skipping property 0003:3905 (UNKNOWN): 1073741824
Skipping property 0102:0FFF (EntryId): ......@..B......+/........../O=NETSENTRAL ...
Skipping property 000B:0E0F (Responsibility): 1
Skipping property 0102:300B (Search Key): EX:/O=NETSENTRAL/OU=FIRST ADMINISTRATIVE  ...
Using    property 001F:39FE (SMTPADDRESS): lars.roald@timpex.no
Skipping property 0102:5FF7 (Recipient EntryId): ......@..B......+/........../o=NETSENTRAL ...
Skipping property 000B:3A40 (Send Rich Info): 1
Skipping property 0003:0C15 (Recipient Type): 1
Skipping property 0003:5FFD (Recipient Flags): 1
Skipping property 0003:0FFE (Object Type): 6
Skipping property 0003:3FDE (Internet Code Page): 65001
Skipping property 0003:3FFD (Message Code Page): 1252
Using    property 001F:0037 (SUBJECT): test ��
Skipping property 0003:6201 (UNKNOWN): 1237491251
Using    property 001F:0C1A (FROM): Lars-Erik Roald
Skipping property 001F:0078 (Received Representing Email Address): /O=NETSENTRAL/OU=FIRST ADMINISTRATIVE GRO ...
Skipping property 001F:0E1D (Normalized Subject): test ��
Skipping property 0003:401B (Received By Flags): 0
Skipping property 0003:0E07 (Message Flags): 1027
Skipping property 001F:001A (Message Class): IPM.Note
Using    property 0102:1013 (BODY_HTML): <meta http-equiv="Content-Type" content=" ...
Skipping property 000B:3016 (UNKNOWN): 1
Skipping property 0102:0C19 (Sender Entry Id): .....+.......n....T.....L.a.r.s.-.E.r.i.k ...
Skipping property 0102:0071 (Conversation Index): ........\...BK......C.
Skipping property 0102:0041 (Sent Representing EntryId): .....+.......n....T.....L.a.r.s.-.E.r.i.k ...
Skipping property 001F:0070 (Conversation Topic): test ��
Skipping property 001F:003D (Subject Prefix): 
Skipping property 0102:65E3 (UNKNOWN): ....P...@...8......o..o
Using    property 001F:0E03 (CC): 
Skipping property 0102:003F (Received By EntryId): ......@..B......+/........../O=NETSENTRAL ...
Skipping property 0003:0036 (Sensitivity): 0
Skipping property 0102:300B (Search Key): BU*..Z.C..+.:.Y.
Skipping property 001F:5D01 (UNKNOWN): lars.roald@gmail.com
Skipping property 001F:8002 (UNKNOWN): 
Skipping property 001F:800B (UNKNOWN): lars.roald@timpex.no
Skipping property 001F:8001 (UNKNOWN): No, score=0.19 tagged_above=-999 required ...
Skipping property 0003:401C (Received Representing Flags): 0
Skipping property 001F:0E02 (Display Bcc): 
Skipping property 001F:8000 (UNKNOWN): by SpamTitan at hatteland.com
Skipping property 0003:65C6 (UNKNOWN): 0
Skipping property 0003:0E17 (UNKNOWN): 0
Skipping property 0003:3FF1 (UNKNOWN): 1044
Skipping property 0003:0FF4 (Access): 2
Skipping property 001F:0076 (Received By Email Address): /O=NETSENTRAL/OU=FIRST ADMINISTRATIVE GRO ...
Skipping property 0040:0E06 (Message Delivery Time): Fri, 15 May 2015 13:34:03 +0000
Skipping property 000B:800A (UNKNOWN): 0
Skipping property 0102:65E0 (UNKNOWN): ...P...@...8......o..H
Skipping property 0102:0043 (Received Representing EntryId): ......@..B......+/........../O=NETSENTRAL ...
Skipping property 001F:0077 (Received Representing Address Type): EX
Skipping property 000B:0059 (UNKNOWN): 1
Skipping property 001F:8007 (UNKNOWN): NO
Skipping property 0102:0C1D (Sender Search Key): SMTP:LARS.ROALD@GMAIL.COM.
Skipping property 0102:0051 (Received By Search Key): EX:/O=NETSENTRAL/OU=FIRST ADMINISTRATIVE  ...
Skipping property 001F:0044 (Received Representing Name): Lars-Erik Roald
Skipping property 0102:002C (UNKNOWN): .... .............B.....lars@timpex.no..
Skipping property 0102:0052 (Received Representing Search Key): EX:/O=NETSENTRAL/OU=FIRST ADMINISTRATIVE  ...
Skipping property 000B:0057 (UNKNOWN): 1
Using    property 001F:0C1E (FROM_ADDR_TYPE): SMTP
Skipping property 000B:0058 (UNKNOWN): 0
Skipping property 0003:0FF7 (Access Level): 0
Skipping property 0003:6200 (UNKNOWN): 2933192712
Skipping property 0102:3014 (UNKNOWN): ....jIn.....
Skipping property 0003:4019 (Sender Flags): 65536
Skipping property 0102:65E2 (UNKNOWN): ...P...@...8......o..o
Skipping property 0102:3FF9 (Creator EntryId): ......@..B......+/........../O=NETSENTRAL ...
Skipping property 0003:4076 (UNKNOWN): 0
Skipping property 0003:0E2F (UNKNOWN): 95610
Skipping property 0102:3FFB (Last Modifier EntryId): .....+.......n....T.....L.a.r.s.-.E.r.i.k ...
Skipping property 001F:8003 (UNKNOWN): v=1; a=rsa-sha256; c=relaxed/relaxed;     ...
Using    property 0102:1009 (BODY_RTF): 0.......LZFu........rcpg125.2.Chtml1.1.bi ...
Skipping property 001F:0042 (Sent Representing Name): Lars-Erik Roald
Skipping property 0102:0E9D (UNKNOWN): ..SMEXutTf4.......
Using    property 001F:1035 (MESSAGEID): <CAKV-B3O9VN+GTySgeHNPUpNG=P5-HJ5k7JKbH8D ...
Using    property 0040:0039 (DATE1ST): Fri, 15 May 2015 13:33:57 +0000
Skipping property 001F:3FFA (Last Modifier Name): Lars-Erik Roald
Using    property 001F:0C1F (FROM_ADDR): lars.roald@gmail.com
Skipping property 0003:0E79 (Trust Sender): 1
Skipping property 0003:401A (Sent Representing Flags): 65536
Using    property 001F:007D (HEAD): Received: from mailfilter03.hatteland.com ...
Skipping property 0003:6827 (UNKNOWN): 2273517951
Using    property 0040:3007 (DATE2ND): Fri, 15 May 2015 13:34:10 +0000
Skipping property 0003:340D (Store Support Mask): 265849
Skipping property 001F:8005 (UNKNOWN): Anonymous
Skipping property 001F:8006 (UNKNOWN): BT=0;II=<invalid>;FIXUP=1,1434;Version=Ve ...
Skipping property 001F:0040 (Received By Name): Lars-Erik Roald
Skipping property 000B:8009 (UNKNOWN): 0
Skipping property 001F:8004 (UNKNOWN): JHSVMHUB01.netsentral.no
Skipping property 000B:0E1F (RTF In Sync): 1
Skipping property 001F:800C (UNKNOWN): 00000003e2010.hatteland.com/o=NETSENTRAL ...
Skipping property 0102:003B (Sent Representing Search Key): SMTP:LARS.ROALD@GMAIL.COM.
Skipping property 001F:3FF8 (Creator Name): Lars-Erik Roald
Skipping property 0003:0017 (Importance): 1
Using    property 001F:0E04 (TO): Lars-Erik Roald
Skipping property 001F:0075 (Received By Address Type): EX
Skipping property 001F:0065 (Sent Representing Email Address): lars.roald@gmail.com
Skipping property 001F:5D02 (UNKNOWN): lars.roald@gmail.com
Skipping property 001F:0064 (Sent Representing Address Type): SMTP
Skipping property 0003:0E23 (Internet Article Number): 95610
Skipping property 001F:1015 (UNKNOWN): E629A2F36F6D33408D89B1474AF25843@netsentr ...
Skipping property 000B:0029 (Read Receipt Requested): 0
Skipping property 0040:3008 (Last Modification Time): Fri, 15 May 2015 13:34:10 +0000
Using    property 001F:1000 (BODY_PLAIN): ��� 
��

Skipping property 001F:8008 (UNKNOWN): 0.19

**Comment by lroal** [comment]
the subject seems to be allright, even though I don't understand it's meaning in the eml: 
?UTF-8?B?dGVzdCDDpsO4w6U=?= 
It somehow gets correct when using mailparser (https://www.npmjs.com/package/mailparser).

**Comment by mvz** [comment]
Converting the sample file finally works correctly with current master of https://github.com/mvz/email-outlook-message-perl
