### ISSUE TITLE
Change i found to fix wide character message

### ISSUE THREAD

**Issue by xylonon** [mvz/msgconvert#5]
error:
Wide character in print at /usr/bin/vendor_perl/msgconvert line 59.

it works by adding

binmode (STDOUT, ":encoding(UTF-8)");

use 5.018;
use diagnostics;
use utf8; # this tells perl that the source code is in utf-8
use open qw( :encoding(utf-8) :std ); # perl will try to open everything in utf-8 mode by default

at the beginning of msgconvert.

**Comment by mvz** [comment]
Closing this since msgconvert is now part of email-outlook-message-perl. See https://github.com/mvz/email-outlook-message-perl/issues/14 for discussion of this issue there.
